### ISSUE TITLE
Maintainers for Netlify

### ISSUE THREAD

**Issue by celestehorgan** [cloudevents/cloudevents-web#59]
Hello cloudevents team!

Currently this site builds via https://app.netlify.com/teams/cloudevents/, and I'm one of two maintainers with (Chris A. being the other) of the Netlify account. 

Please identify 2-3 maintainers who should be added to Netlify and given owner access. You can either leave a response (with email addresses) here or open a service desk ticket: https://cncfservicedesk.atlassian.net/ 

Regards,
Celeste

**Comment by duglin** [comment]
@celestehorgan sorry the very long delay, I just created a service desk ticket

**Comment by duglin** [comment]
Closing since it's now completed
