### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [cloudevents/cloudevents-web#71]
Notice from Netlify:
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

**Comment by nate-double-u** [comment]
Hi, I can help with this. It looks like only CNCF folks are administrators on your Netlify team. (Two others have been invited, but haven't accepted yet).

There should be at least one Maintainer who is a member of the Netlify team -- is there anyone I can invite for this? (Any volunteers?)

**Comment by duglin** [comment]
@nate-double-u who from CloudEvents does it have listed? I'd like to be one of them :-)

**Comment by nate-double-u** [comment]
Hi @duglin, you are listed as invited (using your yahoo email address).

I can reinvite you -- or if you'd like me to use a different email address let me know (you can let me know here, or in the CNCF slack)

@markpeek and @deissnerk are also invited (but still pending, so not accepted)

**Comment by deissnerk** [comment]
I just accepted the invite. I could select another build image. Ubuntu 20.04 seems to be default. 
@nate-double-u What should I do?

**Comment by duglin** [comment]
Yea, go ahead and reinvite me using yahoo

**Comment by nate-double-u** [comment]
@duglin, invite sent.

@deissnerk, thanks. I think the new default should be fine.

**Comment by duglin** [comment]
@nate-double-u ok I think I fixed it! Thanks for the help

**Comment by duglin** [comment]
@nate-double-u we don't seem to be getting any more Netlify builds/checks done as part of our PR process. I see the github webhook being invoked and we get back a 2xx from Netlify but nothing seems to happen. Is it possible to check our Netlify stuff to see if there's something wrong? When I look at the site I don't see anything, but I also can't seem to find any kind of "settings" page for the CE site itself. I kind of wonder if I have permission to see it.

**Comment by duglin** [comment]
@nate-double-u never mind - I think I figured it out :-)

**Comment by nate-double-u** [comment]
Sorry, I just saw this now. I'm glad you got it sorted!
